title: André Oliveira
role: Software Engineer & Tech Lead
description: Professional website showcasing my experience, skills, and projects.
theme: jekyll-theme-minimal
show_downloads: false
github_username:  andrepbo
linkedin_username: andrepbo
email: andre.pbo@gmail.com
google_analytics: "G-N2ZFK52SCV"
lang: pt-BR
locale: pt_BR
url: "https://andrepbo.github.io"
image: /assets/img/andre.jpg
logo: /assets/img/andre.jpg
twitter_username: andrepbo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: /assets/img/andre.jpg
